DO $$ BEGIN
 CREATE TYPE "public"."category" AS ENUM('TypeScript', 'Python', 'C++');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"notes" text,
	"category" "category" NOT NULL,
	"tags" text[] NOT NULL,
	"createdAt" integer DEFAULT extract(epoch from now()) NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "post" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "post_created_at_idx" ON "post" USING btree ("createdAt");